services:

  otel-collector:
    image: otel/opentelemetry-collector:0.86.0
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4317:4317" # OTLP gRPC
      - "55681:55681" # OTLP HTTP

  zipkin:
    image: openzipkin/zipkin:2.24
    ports:
      - "9411:9411"

  postgres:
    image: postgres
    volumes:
      - ./BaseContagemPostgreSql.sql:/docker-entrypoint-initdb.d/1-basecontagem.sql
    environment:
      POSTGRES_PASSWORD: "Postgres2025!"
    ports:
      - "5432:5432"

  mysql:
    image: mysql:9.0
    volumes:
      - ./BaseContagemMySql.sql:/docker-entrypoint-initdb.d/1-basecontagem.sql
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2025!"
      MYSQL_DATABASE: "basecontagem"
    ports:
      - "3306:3306"